[build]
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  CI = "false"
  GENERATE_SOURCEMAP = "false"


[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
